modLoader = "javafml"
# The loader version doesn't matter. Modify the NeoForge and/or Minecraft version ranges instead.
loaderVersion = "[0,)"
issueTrackerURL = "https://github.com/Creators-of-Create/Create/issues"
license = "${mod_license}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/create"
updateJSONURL = "https://api.modrinth.com/updates/create/forge_updates.json?neoforge=only"
logoFile = "icon.png"
authors = "${mod_author}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"

[[dependencies."${mod_id}"]]
modId = "neoforge"
type = "required"
versionRange = "[${neo_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "flywheel"
type = "required"
versionRange = "${flywheel_version_range}"
ordering = "AFTER"
side = "CLIENT"

[[dependencies."${mod_id}"]]
modId = "ponder"
type = "required"
versionRange = "[${ponder_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies."${mod_id}"]]
modId = "create"
type = "required"
versionRange = "[${create_version},)"
ordering = "AFTER"
side = "BOTH"